# Generated by Django 3.1.3 on 2021-06-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NOT_ACTIVE', 'Not active'), ('ONE_MONTH', 'One month'), ('THREE_MONTH', 'Three month'), ('SIX_MONTH', 'Six month')], default='ACTIVE', max_length=30),
        ),
    ]
