# Generated by Django 3.1.3 on 2021-06-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_aboutus_privacytext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='privacytext',
            options={'verbose_name': 'Privacy text', 'verbose_name_plural': 'Privacy text'},
        ),
    ]
