# Generated by Django 3.1.3 on 2021-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0005_auto_20210129_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NOT_ACTIVE', 'Not active')], default='ACTIVE', max_length=30),
        ),
    ]
