# Generated by Django 3.1.3 on 2021-06-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0008_auto_20210619_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cargo',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cargo',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
