# Generated by Django 3.1.3 on 2021-06-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0010_auto_20210619_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='height',
            field=models.FloatField(help_text='Height is optional field', null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='length',
            field=models.FloatField(help_text='Length is optional field', null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='volume',
            field=models.FloatField(help_text='Volume is optional field', null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='width',
            field=models.FloatField(help_text='Width is optional field', null=True),
        ),
    ]
